---
title: "The value of intermediation"
author: "Martin Stancsics"
format:
    revealjs:
        embed-resources: true
        transition: fade
        toc: true
        toc-depth: 1
        toc-title: Agenda
bibliography: references.bib
---

# Intorduction

<style>
    ul li li {
        font-size: 0.75em;
        line-height: 1.2em;
    }
</style>

## Motivation

TODO

## Main ideas

 - Use the Shapley-value instead of an extensive-form bargaining model
    - Analytically more tractable
    - Has bargaining interpretation [e.g. @hart1996bargaining; @gul1989bargaining]
    - Has precedents in the IO literature [e.g. @hart1990property; @montez2007downstream]
 - Focus on the "few large players -- continuum of small players" case (oceanic games)
    - Good approximation of the finite player case even for not too many players
    - Results have a nice geometric interpretation
 - Balance generality and having useful results

## Preview of results

 - The Shapley-value seems to be a very tractable way of modeling bargaining in certain important contexts
    - One/two-sided platforms
    - Upstream-downstream setups
 - Comparative statistics give support to the bargaining interpretation
 - Extensions to include some important cases are relatively straightforward
 - Even a simple application yields interesting results about hybrid platforms


# The Shapley-value

## The Shapley-value

An example game in coalitional form

:::: {.columns}

::: {.column width="50%"}
Imagine a game with three players:

 - A wholesale producer: $P$
 - Two downstream resellers: $A_1, A_2$

:::

::: {.column width="10%"}
:::

::: {.column width="40%"}
And the following achievable profits:

Coalition | Profits
----------|---------
$\{P\},  \{A_i\}$     |  0
$\{A_1, A_2\}$  | 0  
$\{P, A_i\}$  | 2 
$\{P, A_1, A_2\}$  | 3
:::

::::


## The Shapley-value

Each player gets their expected marginal contribution

:::: {.columns}

::: {.column width="50%"}
::: {.r-stack}

::: {.fragment}
   <video data-autoplay src="../../out/manim_figures/videos/shapley_value_demo/800p60/sections/draw_objects.mp4" />
:::
::: {.fragment}
   <video data-autoplay src="../../out/manim_figures/videos/shapley_value_demo/800p60/sections/value_P12.mp4" />
:::
::: {.fragment}
   <video data-autoplay src="../../out/manim_figures/videos/shapley_value_demo/800p60/sections/value_P21.mp4" />
:::
::: {.fragment}
   <video data-autoplay src="../../out/manim_figures/videos/shapley_value_demo/800p60/sections/value_2P1.mp4" />
:::
::: {.fragment}
   <video data-autoplay src="../../out/manim_figures/videos/shapley_value_demo/800p60/sections/value_1P2.mp4" />
:::
::: {.fragment}
   <video data-autoplay src="../../out/manim_figures/videos/shapley_value_demo/800p60/sections/value_12P.mp4" />
:::
::: {.fragment}
   <video data-autoplay src="../../out/manim_figures/videos/shapley_value_demo/800p60/sections/value_21P.mp4" />
:::
::: {.fragment}
   <video data-autoplay src="../../out/manim_figures/videos/shapley_value_demo/800p60/sections/final.mp4" />
:::

:::
:::

::: {.column width="10%"}
:::

::: {.column width="40%"}
And the following achievable profits:

Coalition | Profits
----------|---------
$\{P\},  \{A_i\}$     |  0
$\{A_1, A_2\}$  | 0
$\{P, A_i\}$  | 2 
$\{P, A_1, A_2\}$  | 3
:::

::::


## Why do we care about it?

Same idea as with the Nash bargaining game/solution

 - Axiomatic reasoning
    - The Shapley-value is the only sharing rule that is efficient, symmetric, linear, and satisfies the null player axiom [@shapley1953additive]
 - Bargaining foundations
    - The value arises of the subgame-perfect equilibrium of various alternating-offer bargaining games [e.g. @gul1989bargaining; @winter1994demand; @hart1996bargaining; @stole1996intra; @inderst2003bargaining]
 - A tractable and sensible-looking gain-sharing rule
    - Comparative statics show that it behaves as one would expect


# Main results

## Baseline model

:::: {.columns}

::: {.column width="100%"}

Set of all players: $N = \{P, A_1, \dots, A_n\}$

**Assumption**: the platform is the only way for firms to
reach users and that all $n$ firms are identical
$$
v(C) = \begin{cases}
   0                                           & \text{if } P \notin C \\
   f\left(\frac{|C \setminus \{P\}|}{n}\right) & \text{otherwise}.
\end{cases}
$$
$\forall\, C \subset N$.
:::

::::

## Value of the platform

:::: {.columns}

::: {.column width="40%"}

Characteristic function:
$$
\scriptsize
v(C) = \begin{cases}
   0 \;\text{ if } P \notin C \\
   f\left(\frac{|C \setminus \{P\}|}{n}\right)
\end{cases}
$$

::: {.fragment .fade-in fragment-index=2}
Shapley value:
$$
\scriptsize
\varphi_P^n(f) = \frac{1}{n+1} \sum_{k=0}^{n} f(k)
$$
:::
::: {.fragment .fade-in fragment-index=4}
$$
\scriptsize
\to \int_0^1 f(t) \, \mathrm{d}t
$$
:::

:::

::: {.column width="60%"}

::: {.r-stack}

::: {.fragment fragment-index=1}
   <video data-autoplay src="../../out/manim_figures/videos/proposition_main/800p60/sections/draw_bars.mp4" />
:::
::: {.fragment fragment-index=2}
   <video data-autoplay src="../../out/manim_figures/videos/proposition_main/800p60/sections/add_brace.mp4" />
:::
::: {.fragment fragment-index=3}
   <video data-autoplay src="../../out/manim_figures/videos/proposition_main/800p60/sections/more_firms.mp4" />
:::
::: {.fragment fragment-index=4}
   <video data-autoplay src="../../out/manim_figures/videos/proposition_main/800p60/sections/continuous_approximation.mp4" />
:::
::: {.fragment fragment-index=5}
   <video data-autoplay src="../../out/manim_figures/videos/proposition_main/800p60/sections/surplus_division.mp4" />
:::

:::

:::

::::



## Main proposition

::: {#prp-baseline}
Let $f$ be continuous on $[0, 1]$. Then

$$
\lim_{n \to \infty} \varphi_P^n(f) = \int_0^1 f(t) \, \mathrm{d}t
$$
:::

Even as firms become infinitesimally small, the platform cannot take all the created value


## Simple comparative statics

:::: {.columns}

::: {.column width="40%"}

::: {.fragment fragment-index=1}
The platform gets a larger slice when
:::
::: {.fragment fragment-index=2}
  1. the firms are substitutes to each other
:::
::: {.fragment fragment-index=3}
  2. the platform has intrinsic value
:::
::: {.fragment fragment-index=4}
  3. the fringe firms have no outside option
:::

:::

::: {.column width="60%"}

::: {.r-stack}

::: {.fragment fragment-index=1}
   <video data-autoplay src="../../out/manim_figures/videos/corollary_comparative/800p60/sections/draw_graph.mp4" />
:::
::: {.fragment fragment-index=2}
   <video data-autoplay src="../../out/manim_figures/videos/corollary_comparative/800p60/sections/complements.mp4" />
:::
::: {.fragment fragment-index=3}
   <video data-autoplay src="../../out/manim_figures/videos/corollary_comparative/800p60/sections/intrinsic_value.mp4" />
:::
::: {.fragment fragment-index=4}
   <video data-autoplay src="../../out/manim_figures/videos/corollary_comparative/800p60/sections/outside_option.mp4" />
:::

:::

:::

::::


# Extensions


## Multiple platforms


## Weighted value


# Example application


## Market setup


## Timing of the game


## Results


# Conclusion

## Conclusions

 - Proposed a very tractable way of modeling bargaining applicable to certain important contexts
 - The results are for upstream-downstream situations, platform settings, and two-sided markets
 - The outcomes generally concur with intuitive expectations
 - Even the simple example application provides some interesting insights into hybrid platforms

## Future work

- There is a variety of ways in which the model could be extended (e.g. additional platforms provide some value)
- The example application could be turned into a proper, full-fledged model
- A lab experiment about the outcomes of group bargaining could be conducted
- The model could be applied to other contexts


# Thank you {.unnumbered .unlisted}

## References

::: {#refs}
:::

